version = 1

[[annotations]]
path = "src/**"
precedence = "override"
SPDX-FileCopyrightText = "Amazon.com, Inc. or its affiliates."
SPDX-License-Identifier = "GPL-2.0-only"  # Replaced old short identifier 'GPL-2.0', see https://spdx.org/licenses/GPL-2.0.html
